### ISSUE TITLE
[BUG] Field not found kills server

### ISSUE THREAD

**Issue by general-kroll-4-life** [stackql/stackql#149]
**Describe the bug**
Attempting to query a field that does not exist kills the server

**To Reproduce**
1. Run the following query via the `shell` or `exec`:

```sql
select id, created_at, size_in_bytes
from github.actions.artifacts
where owner = 'stackql' and repo = 'stackql'
```

will get the error (with the current GitHub provider doc):  

```
sql packet preparation error: no such column: id
```
2. Run the same query against the server - it will kill the server process

**Expected behavior**
Should just return a pg error with text similar to what is returned in the `shell`, should **not** kill the server

**Comment by ryukinoz** [comment]
This particular query works with the current provider docs and server versions.

**Comment by ryukinoz** [comment]
Even passing in an egregiously wrong column name has the unwanted effect of adding a static  string, eg:`select id2, created_at, size_in_bytes from github.actions.artifacts where owner = 'stackql' and repo = 'stackql';` the first column is just repeats of the string `id2`. To summarise; this bug has been inadvertently clobbered by another bug that
