### ISSUE TITLE
Unit testing for `garbagecollector` package

### ISSUE THREAD

**Issue by general-kroll-4-life** [stackql/stackql#230]
Add unit testing for `internal/stackql/garbagecollector`.

Acceptance Criteria:

- 85% unit test coverage.

**Comment by ryuichi-maeda** [comment]
@general-kroll-4-life Can I work on this?

**Comment by general-kroll-4-life** [comment]
@ryuichi-maeda defnitely yes, have assigned it to you and moved to in progress.  Thanks again  😎
