### ISSUE TITLE
Unit testing for package `parser`

### ISSUE THREAD

**Issue by general-kroll-4-life** [stackql/stackql#246]
Add unit testing for `internal/stackql/parser`.

Acceptance Criteria:

- 85% unit test coverage.

**Comment by derek10cloud** [comment]
Hi, Can you assign this issue to me?
I would like to work on this issue as my first commit. 😄

**Comment by jeffreyaven** [comment]
done @derek10cloud

**Comment by general-kroll-4-life** [comment]
Closed by https://github.com/stackql/stackql/pull/459 with thanks to @derek10cloud
