### ISSUE TITLE
Add unit testing to package `templatenamespace`

### ISSUE THREAD

**Issue by general-kroll-4-life** [stackql/stackql#277]
Add unit testing for `internal/stackql/templatenamespace `.

Acceptance Criteria:

- 85% unit test coverage.

**Comment by sanketmp** [comment]
can I take this?

**Comment by general-kroll-4-life** [comment]
@sanketmp absolutely please do 🙏

**Comment by sanketmp** [comment]
@general-kroll-4-life 
I have to add a test file to that particular folder right?

**Comment by general-kroll-4-life** [comment]
@sanketmp yes that is the preferred pattern at this stage.  Add test file(s) suffixed with `_test.go` in the target directory.  For this ticket, all test file(s) would reside in the directory `internal/stackql/templatenamespace`.  

I will try and dig up some document that summarises expectations for unit testing.  We do not want to be too opinionated, but some guidance is warranted.  Shall have a bit of a search for some document that hits the right note.
