### ISSUE TITLE
Add unit testing for package `binlog`

### ISSUE THREAD

**Issue by general-kroll-4-life** [stackql/stackql#291]
Add unit testing for `internal/stackql/acid/binlog`.

Acceptance Criteria:

- 85% unit test coverage.

**Comment by BulkBeing** [comment]
@general-kroll-4-life  May I work on this?

**Comment by BulkBeing** [comment]
All uses of `Concatenate` method seems to be:
```go
for _, log := range m.redoLogs {
        rv = rv.Concatenate(log)
}
```

Shall I change the interface to be a variadic function ?
```go
type LogEntry interface {
        .....
	Concatenate(...LogEntry) LogEntry
}
```
This would allow preallocating the slices in the body of `Concatenate` without changing any of the usages of the method in other parts of the code.

**Comment by general-kroll-4-life** [comment]
@BulkBeing  please go ahead.  Full disclosure, this is a future proofing for fully fledged WAL.  You may feel free to suggest improved coding practices as shown.  Thanks for joining in
