### ISSUE TITLE
Add unit testing for package `txn_context`

### ISSUE THREAD

**Issue by general-kroll-4-life** [stackql/stackql#294]
Add unit testing for `internal/stackql/acid/txn_context`.

Acceptance Criteria:

- 85% unit test coverage.

**Comment by Dev79844** [comment]
Hey @general-kroll-4-life! I would like to work on this isssue. Please assign this issue to me

**Comment by rameshgkwd05** [comment]
I am trying this but unable to go beyond 50% coverage

**Comment by rameshgkwd05** [comment]
> I am trying this but unable to go beyond 50% coverage

running go test cover shows 100% coverage 👍
