### ISSUE TITLE
Add unit testing for package `sql_datasource`

### ISSUE THREAD

**Issue by general-kroll-4-life** [stackql/stackql#299]
Add unit testing for `internal/stackql/datasource/sql_data_source`.

Acceptance Criteria:

- 85% unit test coverage.

**Comment by willmadison** [comment]
I'd love for this to be assigned to me. Thanks!

**Comment by general-kroll-4-life** [comment]
@willmadison done, many thanks in advance

**Comment by EraKin575** [comment]
@general-kroll-4-life can I submit a PR. I have it ready

**Comment by general-kroll-4-life** [comment]
@EraKin575 yes please submit a pull request using a fork of this repository.  We will review and run the checks after you have done that.  Thanks for contributing 😎

**Comment by Ashhar-24** [comment]
Hey, I would like to work on this issue.
I'm new to open source, can you please guide me how should I unit testing for the given directory, like what all steps should I follow after cloning the repo.
Could you please guide me through :D

**Comment by Iqbalabdi** [comment]
can i work on this issue?

**Comment by jeffreyaven** [comment]
Sure @Iqbalabdi
