### ISSUE TITLE
Add unit tests for sql_data_table

### ISSUE THREAD

**Issue by Racso-3141** [stackql/stackql#301]
#300

**Comment by Racso-3141** [comment]
#300

**Comment by Racso-3141** [comment]
@jeffreyaven

**Comment by Racso-3141** [comment]
@jeffreyaven The field [colz](https://github.com/stackql/stackql/blob/8e36e6ec9b66384d9617ccd982078820ea77a86f/internal/stackql/datasource/sql_table/sql_table.go#L15) is not initlized in method [NewStandardSQLTable](https://github.com/stackql/stackql/blob/8e36e6ec9b66384d9617ccd982078820ea77a86f/internal/stackql/datasource/sql_table/sql_table.go#L18). 
Should we initialize colz with the input argument like:
```
func NewStandardSQLTable(columns []typing.RelationalColumn) (SQLTable, error) {
	rv := &standardSQLTable{
		symTab: symtab.NewHashMapTreeSymTab(),
		colz:   columns,
	}
	return rv, nil
}
```
or intialize with [NewRelationalColumn](https://github.com/stackql/stackql/blob/8e36e6ec9b66384d9617ccd982078820ea77a86f/internal/stackql/typing/relational_column.go#L41C6-L41C25) like
```
func NewStandardSQLTable() (SQLTable, error) {
	defaultColumns := []typing.RelationalColumn{
		typing.NewRelationalColumn(),
		// Add more columns if needed
	}
	rv := &standardSQLTable{
		symTab: symtab.NewHashMapTreeSymTab(),
		colz:   NewRelationalColumn("name", "type"),
	}
	return rv, nil
}
```

**Comment by general-kroll-4-life** [comment]
@Racso-3141 really appreciate your good work.  

**Short answer**: please do exactly what you have suggested (plus whatever else you are considering) and then raise a PR.  If it passes all unit tests and all of the robot tests pass on the PR run then we shall do code review etc and merge.

**Long answer**:  Looking at the broader codebase, this module is a future proofing that is effectively unused, **but** should come into effect when we get serious about proxying for many different DBAASs.  So this is good stuff for the future.
