### ISSUE TITLE
[QUESTION] releases vs tags

### ISSUE THREAD

**Issue by iMichka** [stackql/stackql#378]
## Question

Hi. Homebrew maintainer here.

We are wondering why not all that's are marked as releases on Github.
Do you want us to update only releases or can we update the stackql package to the latest tag for our users?

For reference
https://github.com/Homebrew/homebrew-core/pull/165656
https://github.com/Homebrew/homebrew-core/pull/165017

Thanks

**Comment by general-kroll-4-life** [comment]
@iMichka thank you for reaching out.  From our point of view, we want to release often and have the latest available to all users.   It is better if you aggressively update homebrew.   Unfortunately we are pretty slow with releasing via git etc, due to some manual stuff.  Full disclosure I don't know anything about `brew bump`; is there anything we can do to make this easier or configure our formula to clarify what is desirable?

**Comment by iMichka** [comment]
No need for `brew bump`: we check at least daily if there is an update on your repo, and will update the package accordingly. It's automatised. There are ways to push the releases from your side to homebrew (in case you want to get things shipped really really fast).

The issue we have right now is that there is a mismatch between this page https://github.com/stackql/stackql/releases, that defines the last release, and the two last tags. We have projects that will use tags as "beta" versions, or even move tags around (which is bad). This is why we prefer releases on top of tags. And we are often worried when we see new tags appear, but no new release.

**Comment by jeffreyaven** [comment]
hi @iMichka we are happy with releases, we generally create a stable release from tags once a month or so, although there may be one or more PRs to main and tagged builds in between, we create the releases manually and then add artifacts to the release (like Signed Windows MSI packages and MacOS notarized PKG files), we then create Chocolatey packages separately through another process, this is all semi-automated (scripted but manually triggered).  Long story short, happy to use new releases to create new Homebrew packages if that's what you prefer.

**Comment by iMichka** [comment]
It depends on what you prefer: do you want us to ship releases, or each single tag (even if there is no associated release) ?

**Comment by jeffreyaven** [comment]
lets do releases @iMichka

**Comment by chenrui333** [comment]
@jeffreyaven thanks for clarifying, can you generate the release notes for both `v0.5.589` and `v0.5.591` tags? Once that is done, we (homebrew) can just ship [this PR](https://github.com/Homebrew/homebrew-core/pull/165656) out

**Comment by jeffreyaven** [comment]
Hi @chenrui333, Ill create a release for `v0.5.591` and generate release notes later today (wont bother with `v0.5.589`, let you know when its ready

**Comment by chenrui333** [comment]
yeah, thanks @jeffreyaven! 🙏

**Comment by jeffreyaven** [comment]
here you go @chenrui333 [`v0.5.591`](https://github.com/stackql/stackql/releases/tag/v0.5.591)

**Comment by chenrui333** [comment]
Thanks, i guess this can be closed via https://github.com/Homebrew/homebrew-core/pull/165656
