### ISSUE TITLE
mark 0.5.742 as a release

### ISSUE THREAD

**Issue by chenrui333** [stackql/stackql#467]
👋 looks like 0.5.742 did not get marked as a release, raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/190909

**Comment by jeffreyaven** [comment]
Hi @chenrui333 will be marked as a release today

**Comment by jeffreyaven** [comment]
done @chenrui333 !

**Comment by jeffreyaven** [comment]
done @chenrui333 ! https://github.com/stackql/stackql/releases/tag/v0.5.742
