### ISSUE TITLE
mark 0.5.748 as latest release?

### ISSUE THREAD

**Issue by chenrui333** [stackql/stackql#471]
👋 it looks like there is no github release for 0.5.748, raise this issue for some awareness, thanks!

<img width="514" alt="image" src="https://github.com/user-attachments/assets/ff32041e-e691-4c3a-a053-f93fb9ec08e2">

relates to https://github.com/Homebrew/homebrew-core/pull/192452

**Comment by jeffreyaven** [comment]
hi @chenrui333 marked as release now

**Comment by chenrui333** [comment]
Thanks @jeffreyaven!
